### NumPy Library

In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


### Dimensions in array

In [6]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


### 1 d array

In [7]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


### 2 d array

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


### 3 d array

In [11]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


### Check Number of Dimensions?

In [12]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
 - An array can have any number of dimensions.
 - When the array is created, you can define the number of dimensions by using the ndimn argument.

#### Create an array with 5 dimensions and verify that it has 5 dimensions:

In [16]:
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print("number of dimensions:", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [17]:
a = np.array([[[[[1,2,3,4]]]]])
print(a)
print(a.ndim)

[[[[[1 2 3 4]]]]]
5


### NumPy Array Indexing
- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.
- The indexes in NumPy arrays start with 0. meaning that the first element has index 0. and the second has index 1 etc.

#### Get the first element from the following array:

In [18]:
arr = np.array([1,2,3,4])
print(arr[0])

1


#### get third and sixth and 8th elements from the following array and add them.

In [19]:
m = np.array([41,87,34,56,8,39,23,90,15,10,19,56])
print("the second element is",m[2])
print("the sixth element is",m[5])
print("the 8th element is",m[7])
print("sum of this elements are", m[2]+m[5]+m[7])

the second element is 34
the sixth element is 39
the 8th element is 90
sum of this elements are 163


### Access 2-D Arrays
- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
- Think of 2-D arrays like a table with rows and columns,where the dimension represents the row and the index represents the column.

In [20]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("2nd element on 1st row:",arr[0,1])

2nd element on 1st row: 20


In [21]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("4th element on 1st row:",arr[0,3])

4th element on 1st row: 40


In [22]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("1st element on 1st row:",arr[1,0])

1st element on 1st row: 60


In [23]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("last element on 2nd row:",arr[1,4])

last element on 2nd row: 100


#### add the first element of row 1 and last element